# Estrutura de dados

##Manipulação de Variaveis

###Numeros Inteiros

In [ ]:
num = 3
num1 = 5
num_jpg = 13
num_conv = 15

In [ ]:
num1

5

In [ ]:
print(num1, num_conv)

5 15


###Números Reais

In [ ]:
pi = 3.142345


In [ ]:
pi


3.142345

###Strigs e chars

In [ ]:
letra = 'a'
palavra1 = 'estrutura de dados'
palavra2 = 'python'
pi

3.142345

In [ ]:
print(letra, palavra1)

a estrutura de dados


In [ ]:
print('estou aprendendo uma ', palavra1)
print('esta', palavra1, 'aplicado em', palavra2)

estou aprendendo uma  estrutura de dados
esta estrutura de dados aplicado em python


In [ ]:
idade = int(input('digite sua idade'))

digite sua idade33


In [ ]:
p = input('qual é a sua altura?')
print('sua altura é ',p)

qual é a sua altura?1,65
sua altura é  1,65


In [ ]:
nome  = str(input('qual é seu nome?'))
print('seu nome é', nome)

qual é seu nome?asdasddasd
seu nome é asdasddasd


In [ ]:
idade

33

###manipulação de Strings


In [ ]:
a = 'alexandredfghdfgdfgdfgdfg'
print(a)


alexandredfghdfgdfgdfgdfg


In [ ]:
maiuscula = a.upper()
print(maiuscula)

ALEXANDREDFGHDFGDFGDFGDFG


In [ ]:
miniscula = a.lower()
print(miniscula)

alexandredfghdfgdfgdfgdfg


In [ ]:
cap = a.capitalize()
print(cap)

Alexandredfghdfgdfgdfgdfg


In [ ]:
parte_palavra = a[0:3]
print(parte_palavra)

ale


In [ ]:
ultimas_letras = a[3:]
print(ultimas_letras)

xandredfghdfgdfgdfgdfg


In [ ]:
b = a.replace('xjhjke', 'xandra')

print(a)
print(b)

alexandredfghdfgdfgdfgdfg
alexandredfghdfgdfgdfgdfg


In [ ]:
b.find('e')

2

####-1 letra nao encotrada

In [ ]:
b.find('s')

-1

In [ ]:
print(len(b))

25


In [ ]:
c = '        dia  D      '
print(len(c))


20


In [ ]:
rr = '3'
ee = int(rr)
print(5*ff)
print(5*ee)


55555
15


In [ ]:
print(len(c))
f = c.strip()
print(f)
print(len(f))


20
dia  D
6


In [ ]:
print(len(c))


20


In [ ]:
nn1 = '14'
nn2 = '16'
n1 = int(nn1)
n2 = int(nn2)

In [ ]:
print(f'dividindo{n1} por {n2} o resultado e {n1/n2}')
print(f'dividindo n1 por n2 o resultado e n1/n2')
print('dividindo n1','por n2 o resultado e n1/n2',sep='')

dividindo14 por 16 o resultado e 0.875
dividindo n1 por n2 o resultado e n1/n2
dividindo n1por n2 o resultado e n1/n2


##Opérações Matemáticas

In [ ]:
a = 5
b = 3


In [ ]:
print(a,b)

5 3


In [ ]:
a + b

8

In [ ]:
print(' a soma é ', a + b)

 a soma é  8


In [ ]:
print(' a subtração é ', a - b)

 a subtração é  2


In [ ]:
print(' a Divisão é ', a / b)

 a Divisão é  1.6666666666666667


In [ ]:
print(' a multiplicação  é ', a * b)

 a multiplicação  é  15


In [ ]:
print(' o resto da divisão é ', 10 % 2)

 o resto da divisão é  0


In [ ]:
print(' o resto da divisão é ', 11 % 2)

 o resto da divisão é  1


In [ ]:
print(' 5 elevado a 3  é ', 5**2)

 5 elevado a 3  é  25


In [ ]:
import math
math.sqrt(9)

3.0

##Arredondamento

In [ ]:
casos_doença = 134
numero_habitantes = 3444
casos_por_habitantes = casos_doença  / numero_habitantes
print(casos_por_habitantes)

0.038908246225319396


In [ ]:
round(casos_por_habitantes, 3)

0.039

In [ ]:
print(' o numere é ', round(casos_por_habitantes,4))

 o numere é  0.0389


###exercicio
ler 2 numeros
calculos

In [ ]:
n3 = int(input('digete o primeiro numero '))
n4 = int(input('digete o segundo numero '))



digete o primeiro numero 3
digete o segundo numero 4


In [ ]:
ad = n3 + n4
sub = n3 - n4
mult = n3 * n4
div = n4 / n3
elevado = n3**n4

print('adição ', ad)
print('substração ', sub)
print('multiplicação ', mult)
print('divisão ', round(div, 1))
print('n3 elevado a n4 ', elevado)

In [ ]:
print('adição ', ad)
print('substração ', sub)
print('multiplicação ', mult)
print('divisão ', round(div, 1))
print(f'{n3} elevado a {n4}', elevado)

adição  7
substração  -1
multiplicação  12
divisão  1.3
3 elevado a 4 81


#Operadores Lógicos

In [ ]:
a = True
b = False


In [ ]:
print(a,b)

True False


In [ ]:
a and b

False

In [ ]:
a & b

False

In [ ]:
c = a & b
print("'a' e 'b' são iguais  ", c)

'a' e 'b' são iguais   False


In [ ]:
a or b

True

In [ ]:
a | b


True

In [ ]:
not a

False

In [ ]:
not b

True

In [ ]:
5 < 3

False

In [ ]:
5 >= 3

True

In [ ]:
5 == 3

False

In [ ]:
5 != 3

True

# operador condicional

In [ ]:
5 > 3


True

In [ ]:
if 5 > 7:
  print('5 é maior que 3')
else:
  print('e menor que')

e menor que


#estrutura de repetição

###FOR

In [ ]:
for n in range(1,6,2):
  print(n)

1
3
5


In [ ]:
for n in range(5, 0, -2):
  print(n)

5
3
1


In [ ]:
soma = 0
for n in range(1,6):
  {
    soma = soma + n
  print(soma)
}

print(soma)

1
3
6
10
15
15


In [ ]:
palavra = 'palavra'
for letra in palavra:
  print(letra)
  if letra == 'v':
    print('ACHOU')

p
a
l
a
v
ACHOU
r
a


In [ ]:
for i in range(0,5):
 print(i)
 print('---')
 for j in range(0, 4):
   print('-', j)
 print()

0
---
- 0
- 1
- 2
- 3

1
---
- 0
- 1
- 2
- 3

2
---
- 0
- 1
- 2
- 3

3
---
- 0
- 1
- 2
- 3

4
---
- 0
- 1
- 2
- 3



In [ ]:
nome = input('entre com seu nome :')
idade = int (input ('entre com sua idade:'))
if idade >= 18:
  print(' vc é maior de idade ')
  for i in range (idade, 0, -1):
    print (i)
    print(25*'-')
  for i in range (31, -1, -2):
    print (i)
    print(25*'-')
  for i in range (3, 20, 2):
    print (i)
else:
  for i in range (0, idade):
    print(i)

entre com seu nome :aaa
entre com sua idade:22
 vc é maior de idade 
22
-------------------------
21
-------------------------
20
-------------------------
19
-------------------------
18
-------------------------
17
-------------------------
16
-------------------------
15
-------------------------
14
-------------------------
13
-------------------------
12
-------------------------
11
-------------------------
10
-------------------------
9
-------------------------
8
-------------------------
7
-------------------------
6
-------------------------
5
-------------------------
4
-------------------------
3
-------------------------
2
-------------------------
1
-------------------------
31
-------------------------
29
-------------------------
27
-------------------------
25
-------------------------
23
-------------------------
21
-------------------------
19
-------------------------
17
-------------------------
15
-------------------------
13
-------------------------
11
---------

###WHILE

In [ ]:
n = 1
while n < 6:
 print(n)
 n += 1
print('---')

1
2
3
4
5
---


In [ ]:
s = 0
n1 = 1
while n1 < 6:
  s += n1
  n1 += 1
print(s)

15


In [ ]:
for i in range(1, 11, 1):
  print('3 x {} = {}'.format(i, 3 * i))

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30


#Coleções

#Tuplas

In [ ]:
tupla = ('aaaaa', 1, 'ccccccc')

In [ ]:
tupla

('aaaaa', 1, 'ccccccc')

In [ ]:
tupla[1]

1

In [ ]:
tupla.index('aaaaa')

0

In [ ]:
for el in tupla:
  print(el)

aaaaa
1
ccccccc


#Listas

In [ ]:
l1 = ['aaaaa', 'bbbbbb', 'ccccccc']
l2 = ['111111', 'bb22222', '33cccc']

In [ ]:
l3 = l1 + l2

In [ ]:
l3

['aaaaa', 'bbbbbb', 'ccccccc', '111111', 'bbbbbb22222', '333333ccccccc']

In [ ]:
l2_2 = l2 * 2

In [ ]:
l2_2

['111111', 'bb22222', '33cccc', '111111', 'bb22222', '33cccc']

In [ ]:
l1 [0:2]

['aaaaa', 'bbbbbb']

In [ ]:
l1.append('aaasdasdasd')

In [ ]:
l1

['aaaaa', 'bbbbbb', 'ccccccc', 'aaasdasdasd']

In [ ]:
del(l1)

In [ ]:
for k in l2_2:
  print(k)

111111
bb22222
33cccc
111111
bb22222
33cccc


In [ ]:
lista_A = ['11111' , '222222' , '33333333']
lista_B = [ ]
lista_C = [ ]

print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')

lista_A = [ '222222' , '33333333']
lista_B = [ ]
lista_C = [ '11111']


print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')


lista_A = [  '33333333']
lista_B = [ '222222']
lista_C = [ '11111' ]


print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')


lista_A = [  '33333333']
lista_B = [ '11111' , '222222']
lista_C = [  ]


print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')


lista_A = [  ]
lista_B = [ '11111' , '222222']
lista_C = [ '33333333' ]


print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')

lista_A = [ '11111'  ]
lista_B = [  '222222']
lista_C = [ '33333333' ]


print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')

lista_A = [ '11111'  ]
lista_B = [  ]
lista_C = [ '222222' , '33333333' ]


print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')



lista_A = [   ]
lista_B = [  ]
lista_C = [ '11111' , '222222' , '33333333' ]


print ('A', lista_A)
print ('B', lista_B)
print ('C', lista_C)
print (20*'#')

A ['11111', '222222', '33333333']
B []
C []
####################
A ['222222', '33333333']
B []
C ['11111']
####################
A ['33333333']
B ['222222']
C ['11111']
####################
A ['33333333']
B ['11111', '222222']
C []
####################
A []
B ['11111', '222222']
C ['33333333']
####################
A ['11111']
B ['222222']
C ['33333333']
####################
A ['11111']
B []
C ['222222', '33333333']
####################
A []
B []
C ['11111', '222222', '33333333']
####################


#Dicionários

In [ ]:
coleta = {'aaaasss':22, 'qwerqweqe':333, 'asdasdasdgeergwerf':444, 'aa':23, 'aaa':3}

In [ ]:
coleta

{'aaaasss': 22, 'qwerqweqe': 333, 'asdasdasdgeergwerf': 444, 'aa': 3}

In [ ]:
print(coleta)

{'aaaasss': 22, 'qwerqweqe': 333, 'asdasdasdgeergwerf': 444, 'aa': 3}


In [ ]:
coleta['aa']

33

In [ ]:
coleta['gggggg'] = 77

In [ ]:
print (coleta)

{'aaaasss': 22, 'qwerqweqe': 333, 'asdasdasdgeergwerf': 444, 'aa': 3, 'gggggg': 77}


In [ ]:
del(coleta) ['aaaasss']
print(coleta)

{'qwerqweqe': 333, 'asdasdasdgeergwerf': 444, 'aa': 3, 'gggggg': 77}


In [ ]:
print(coleta)

{'qwerqweqe': 333, 'asdasdasdgeergwerf': 444, 'aa': 3, 'gggggg': 77}


In [ ]:
coleta.items()

dict_items([('qwerqweqe', 333), ('asdasdasdgeergwerf', 444), ('aa', 3), ('gggggg', 77)])

In [ ]:
coleta.keys()

dict_keys(['qwerqweqe', 'asdasdasdgeergwerf', 'aa', 'gggggg'])

In [ ]:
coleta.values()

dict_values([333, 444, 3, 77])

In [ ]:
col2={'rrrrr':11, 'uuu':999}
print(col2)

{'rrrrr': 11, 'uuu': 999}


In [ ]:
coleta.update(col2)
print(coleta)

{'aaaasss': 22, 'qwerqweqe': 333, 'asdasdasdgeergwerf': 444, 'aa': 33, 'rrrrr': 11, 'uuu': 999}


In [ ]:
coleta.items()

dict_items([('aaaasss', 22), ('qwerqweqe', 333), ('asdasdasdgeergwerf', 444), ('aa', 33), ('rrrrr', 11), ('uuu', 999)])

In [ ]:
for ts, num in coleta.items():
  print(f'teste: {ts}, numero: {num}')

teste: aaaasss, numero: 22
teste: qwerqweqe, numero: 333
teste: asdasdasdgeergwerf, numero: 444
teste: aa, numero: 33
teste: rrrrr, numero: 11
teste: uuu, numero: 999


#Conjuto(set)

In [ ]:
b1 = ('ss', 'asd', 'fff', 'fff', 'ss')

In [ ]:
print(b1)

('ss', 'asd', 'fff', 'fff', 'ss')


In [ ]:
print(set(b1))

{'fff', 'asd', 'ss'}


In [ ]:
c1 = {1,2,3,4,5}
c2 = {3,4,5,6,7,8}
c3 = c1.intersection(c2)

In [ ]:
print(c3)

{3, 4, 5}


In [ ]:
c1.difference(c2)

{1, 2}

In [ ]:
c2.difference(c1)

{6, 7, 8}

#Matrizes

In [ ]:
import numpy as np

In [ ]:
mt = np.array([[2,3,4], [4,5,7]])


In [ ]:
mt

array([[2, 3, 4],
       [4, 5, 7]])

In [ ]:
mt.shape

(2, 3)

In [ ]:
mt[0]

array([2, 3, 4])

In [ ]:
mt[1]

array([4, 5, 7])

In [ ]:
mt[0][2]

4

In [ ]:
mt[1][2]

7

In [ ]:
for i in range(mt.shape[0]):
  print(mt[i])
  for j in range(mt.shape[1]):
    print(mt[i][j])

[2 3 4]
2
3
4
[4 5 7]
4
5
7


In [ ]:
num_alunos = int(input('entre com o numero de alunos:'))
num_notas = int(input('ente com o numeros de notas:'))
turma1 = [ ]
notas1 = [ ]
for i in range(0,num_alunos):
  nome = input('digite o nome : ')
  turma1.append(nome)
  for j in range (num_notas):
    nota = float(input('digite a nota: '))
    notas1.append(nota)
print (turma1)
print (notas1)

entre com o numero de alunos:2
ente com o numeros de notas:2
digite o nome : aaaa
digite a nota: 3
digite a nota: 4
digite o nome : bbbbb
digite a nota: 5
digite a nota: 6
['aaaa', 'bbbbb']
[3.0, 4.0, 5.0, 6.0]


In [ ]:
num_alunos = int(input('entre com o numero de alunos:'))
num_notas = int(input('ente com o numeros de notas:'))
turma1 = [ ]
notas1 = [ ]
for i in range(num_alunos):
  turma1.append(input('digite o nome : '))
  for j in range (num_notas):
    notas1.append(float(input('digite a nota: ')))
  turma1.append(notas1)
print (turma1)


entre com o numero de alunos:2
ente com o numeros de notas:2
digite o nome : aaaa
digite a nota: 2
digite a nota: 3
digite o nome : ffff
digite a nota: 4
digite a nota: 5
['aaaa', [2.0, 3.0, 4.0, 5.0], 'ffff', [2.0, 3.0, 4.0, 5.0]]


In [ ]:
linha = int(input('entre com o numero de linhas:'))
colunas = int(input('ente com o numeros de colunas:'))
turma = int(input('ente com o numeros de turma'))
turma1 = [ ]

for k in range (turma):
  matriz1 = [ ]
  for i in range (linha):
    linha1 = [ ]
    for j in range (colunas):
      linha1.append(float(input('digite um numero: ')))
      print(linha1)
    matriz1.append(linha1)
    print (matriz1)
  turma1.append(matriz1)
print (turma1)


entre com o numero de linhas:2
ente com o numeros de colunas:2
ente com o numeros de turma2
digite um numero: 1
[1.0]
digite um numero: 2
[1.0, 2.0]
[[1.0, 2.0]]
digite um numero: 3
[3.0]
digite um numero: 4
[3.0, 4.0]
[[1.0, 2.0], [3.0, 4.0]]
digite um numero: 5
[5.0]
digite um numero: 6
[5.0, 6.0]
[[5.0, 6.0]]
digite um numero: 7
[7.0]
digite um numero: 8
[7.0, 8.0]
[[5.0, 6.0], [7.0, 8.0]]
[[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]]


## EX1 Lista2

In [ ]:
lista = []
for _ in range(1,6):
  valor = int(input('digite o Valor: '))
  lista.append(valor)

digite o Valor: 1
digite o Valor: 2
digite o Valor: 3
digite o Valor: 4
digite o Valor: 5


In [ ]:
soma = 0
for i in range(len(lista)):
  print(lista[i])
  soma += lista[i]
print(soma)



1
2
3
4
5
15


In [ ]:
import numpy as np
np.array(lista).sum()

15

##EX Dic

In [ ]:
alunos = {}
for _ in range(1, 4):
  nome = input('digite o nome : ')
  nota = float(input('digite a nota: '))
  alunos[nome] = nota


digite o nome : ale
digite a nota: 4
digite o nome : ser
digite a nota: 3
digite o nome : cas
digite a nota: 1


In [ ]:
alunos

{'ale': 4.0, 'cas': 1.0, 'ser': 3.0}

In [ ]:
alunos['ale']

4.0

In [ ]:
alunos.values()

dict_values([4.0, 3.0, 1.0])

In [ ]:
soma = 0
for nota in alunos.values():
  print(nota)
  soma += nota
print('media: ', soma/3)

4.0
3.0
1.0
media:  2.6666666666666665


##Ex Matriz

In [ ]:
matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])
matriz

array([[3, 4, 1],
       [3, 1, 5]])

In [ ]:
matriz.shape

(2, 3)

In [ ]:
soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j])
    soma = matriz[i][j]
print('soma: ', soma)

3
4
1
3
1
5
soma:  17


#Funções

## Função sem parametro e sem retorno

In [ ]:
def mensagem():
  print('teste da função')

In [ ]:
mensagem()
mensagem()
mensagem()

teste da função
teste da função
teste da função


## Função com passagem de parametro

In [ ]:
def mensagem(texto):
  print(texto)

In [ ]:
mensagem('tsdfsdfsdf')
mensagem('texto sdfasfas2')
mensagem('textsadfsfasdfo 3')

tsdfsdfsdf
texto sdfasfas2
textsadfsfasdfo 3


In [ ]:
def soma(a,b):
  print(a + b)

In [ ]:
soma(244, 3444)

3688


In [ ]:
soma(3, 3)
soma(33, 43)

6
76


## Função com passagem de parametro e retorno

In [ ]:
def soma(a,b):
  return a + b

In [ ]:
soma(3, 4)

7

In [ ]:
r = soma(3, 2)
print(r)

5


In [ ]:
def calcula(m, h, g = 10):
  '''
  descriçao da função
  blablablablablablablablablabla
  blablablablablablablabla
  blablablablablablablabla
  '''
  e = g * h * m
  return e


In [ ]:
calcula(10, 12)

1200

In [ ]:
calcula(10, 12, 9.8)

1176.0

In [ ]:
help(calcula)

Help on function calcula in module __main__:

calcula(m, h, g=10)
    descriçao da função
    blablablablablablablablablabla
    blablablablablablablabla
    blablablablablablablabla



#Modulos Math, datetime, random e time

#Modulos personalisados
#### abrir anaconda depois spyder e implenetar o modulo que deseja em py

In [ ]:
import modulo_personalisado as ut

In [ ]:
ut.soma(1,2,3)

6

In [ ]:
ut.mult(4,2,3)

24

In [ ]:
ut.palind('abccba')

True

In [ ]:
t = 'abccba'

In [ ]:
t[::-1]

'abccba'

In [ ]:
t1 = 'abc'
t1[::-1]

'cba'

In [ ]:
ut.div(8,4)

2.0

#Manipulação de Arquivos

In [ ]:
with open('/content/frases.txt') as text:
  for linha in text:
   print(linha)

olá

Os ponteiros podem existir nativamente no Python?

 Provavelmente, mas aparentemente, os indicadores contradizem o conceito de Zen de Python 

blablablablablablablabla

blablablablablablablablablabla

blablablablablablablablablablablabla

blablablablablabla


In [ ]:
with open('/content/frases.txt', 'r') as text:
  for linha in text:
   print(linha)

olá

Os ponteiros podem existir nativamente no Python?

 Provavelmente, mas aparentemente, os indicadores contradizem o conceito de Zen de Python 

blablablablablablablabla

blablablablablablablablablabla

blablablablablablablablablablablabla

blablablablablabla


In [ ]:
with open('/content/frases.txt') as text:
  r = text.readlines()

In [ ]:
r

['olá\n',
 'Os ponteiros podem existir nativamente no Python?\n',
 ' Provavelmente, mas aparentemente, os indicadores contradizem o conceito de Zen de Python \n',
 'blablablablablablablabla\n',
 'blablablablablablablablablabla\n',
 'blablablablablablablablablablablabla\n',
 'blablablablablabla']

In [ ]:
with open('texto2.txt', 'w') as texto:
  texto.write('olaaaaaaa todos')

In [ ]:
with open('texto2.txt', 'r') as text:
  for linha in text:
   print(linha)

olaaaaaaa todos


#Vetor não Ordenado